firebase:
  service_account: "./service-account.json"
  database_url: "https://number-baseball-28392-default-rtdb.firebaseio.com"

bot:
  name: "CPU-Intermediate"
  group_code: "L02"
  strategy: "elimination"
  level: 2
  restart_delay_seconds: 3
  guess_delay_seconds: 3.0
  heartbeat_interval: 15
  error_rate: 0.4
